### ISSUE TITLE
Всякое разное

### ISSUE THREAD

**Issue by AlexeiCrystal** [The-F-Project/EduCA#1]
![Screenshot_2024-12-24-10-01-55-548-edit_org thefproject fedu](https://github.com/user-attachments/assets/ec1daf68-e3bb-4512-82bd-b995d6bf7817)
1. В 7 классе учебники алгебры и геометрии попутаны местами.

2. Ещё почему то в 7 и 8 Искусство называется Черчение хотя это не так.

3. В 9 классе часть учебников не рабочая, часть перекидывает на гдз хотя это раздел учебников а не гдз. Физика перекидывает на биологию.

4. В 10 геометрия и физика перекидывает на биологию.
Ты бы хотя бы по названию файлов глядел что ты добавляешь.

5. Ещё не все учебники, например труды, химия и тд

6. Календарь контрольных работ "Page not found"

7. Кнопки на экране не всегда равномерно расположены.

8. Дата и время выглядят немножко не очень, и время обновляется только после перехода в приложение.

9. В гдз хотелось бы видеть тетради на печатной основе и контурные карты которые все под начало года покупают и они с лабораторками, практическими, картами. Такие есть по биологии, физике, географии, химии и вроде всё. 

10. Ещё некоторые кнопки перекидывают в браузер а некоторые открываются в самом приложении. Хотя хотелось бы чтобы всё в приложении.

11.Кнопка проверять бета-версии после выхода со страницы проверки обновлений сбрасывается.

12. Ещё не хватает слитых заданий, текстов изложений, самостоялок, контрольных. Они есть например в тг.
Я ещё могу некоторыми работами и их датами (для календаря) поделиться

Ещё можно чтобы была история открытия учебников, гдз
И чтобы в настройках можно было выбрать основной класс (в которым ты сейчас) чтобы гдз и учебники на этот класс показывались первее всех в списке или сразу открывался список с учебниками этого класса а не выбор класса и снизу можно было поглядеть другой класс

Кнопка "Следующая страница" не работает

Вроде после 9 там одна история (но это не точно), но до этого есть и всемирная и история Беларуси. И поэтому лучше писать на кнопках какая именно история и добавлять и на то и на другое гдз и PDF файлы учебников

Нижние кнопки в некоторых разделах не работают, например в разделе проверки обновлений

**Comment by FaliedDedd** [comment]
Привет, огромное спасибо за подробный разбор ошибок которые присутствуют. Мнение и советы учту. Многое уже исправлено но не выпущено(готовлю все к следующему выпуску, слишком многое изменено чтобы делать промежуточную версию, так что выпущу позже) в любом случае спасибо
