### ISSUE TITLE
Всякое разное 2

### ISSUE THREAD

**Issue by AlexeiCrystal** [The-F-Project/EduCA#2]
В справочнике не мешало бы распределить по разделам разные темы и сделать поиск.

И ещё не знаю с чем связано и у всех ли это, но почему-то именно загрузка этого приложения именно из GitHub почему-то слишком медленная. Хотя интернет хороший и всё остальное скачивается быстро.

Календарь контрольных работ конечно прикольно, но у всех может быть по разному, немного в разные даты.

Ещё я скоро опубликую файлы твоего приложения на trashbox, мб там загрузка быстрее будет. Но пока в черновиках так как у тебя сильно много версий и загрузка медленная.
![Screenshot_2024-12-26-20-44-14-059_com yandex searchapp beta](https://github.com/user-attachments/assets/3c6e856f-e63d-4bf4-88c1-42d1913af09e)

**Comment by FaliedDedd** [comment]
Приветствую, календарь ещё в процессе. Я сделаю разбивку по школам, и ученики будут сами вносить данные. А загрузка медленная именно с сервера git, повлиять я на это не могу. Я сейчас активно работаю над приложением и стараюсь его закончить до нг
