### ISSUE TITLE
Всякое разное 3

### ISSUE THREAD

**Issue by AlexeiCrystal** [The-F-Project/EduCA#3]
Твои приложения уже на trashbox:
https://trashbox.ru/topics/186705/educa
https://trashbox.ru/topics/186732/taco
Но пока на модерации.
Или же всё же удалить EduCA? Просто такое недавно тоже добавили, но там только одна версия. Плюс ещё тот EduCA немножко неправильно опубликован, в раздел картинки а не приложения. В следствии чего фото расположены в столбик а не в ряд, нет кнопки скачать и приходится пролистывать вниз. Да и вообще раздел картинок не предназначен для приложений. И скорее всего модерация удалит это. (https://trashbox.ru/topics/186714/educa)
Upd: модерация уже убрала, так что скорее всего я удалять свой пост не буду.

Оффлайн ГДЗ нужно на разные классы, ещё там не везде можно приближать и отдалять, если зайти с интернетом то просто вылетает. Если попытаться зайди через EduCA пишет приложение не установлено.

А ещё зачем приложению доступ к рекламному индефикатору. Ты планируешь вводить рекламу? Или это для блокировки рекламы в гдз?
![IMG_20241227_110555](https://github.com/user-attachments/assets/cf55d581-8f15-4530-8504-dd44e3be0466)

**Comment by FaliedDedd** [comment]
Привет огромное спасибо за публикацию на trashbox. Рекламу я вводить не собираюсь, я использую google аналитику, а увы все что связано с гугл связано и с сбором рекламных данных. А сам я рекламу не буду вводить 
![изображение](https://github.com/user-attachments/assets/edea6452-8333-4f10-a6d4-760aa841065d)
Версия 1.20 - 1.21 являются тестовыми, я не закончил над ними работу и не отправил в релиз. О сообщенных ошибках спасибо, сегодня исправлю

**Comment by AlexeiCrystal** [comment]
На trashbox уже можно скачать. Модераторы всё проверили.
