### ISSUE TITLE
Ещё что то

### ISSUE THREAD

**Issue by AlexeiCrystal** [The-F-Project/EduCA#6]
Кнопки в главном меню наконец-то не поехавшие. Но там где нужно скачивать учебники там нету отступов кнопок друг от друга и они ещё друга на друга даже накладываются, и нет второй части по рус литу
Физика до сих пор везде открывает биологию, а биология ничего не открывает. В 7 классе алгебра открывает геометрию, а геометрия алгебру

Ещё Taco вылетает при проверке обновлений.
![IMG_20241228_123514](https://github.com/user-attachments/assets/f1e06bb1-a0dd-4c92-854e-c9a15efee6ba)

Что касается каталога полезных приложений про которые я как то говорил можно например:
Photomath: https://play.google.com/store/apps/details?id=com.microblink.photomath
Для алгебры, платных подписок вроде бы тут пока нет.

Таблица Менделеева (Для химии):
Обычная: https://play.google.com/store/apps/details?id=mendeleev.redlime
Pro версия: https://play.google.com/store/apps/details?id=august.mendeleev.pro
Взломка Pro версии: https://s1.spiderdown.com/Periodic%20Table%202022%20PRO/Periodic%20Table%20PRO%20v3.5.7%20%28Patched%29.apk

И всякое подобное. И можно попробовать встроить какой то функционал в твоё приложение если хочешь.

Ещё можно сделать каталог с изложениями, диктантами и тд. В котором можно по названию или по каким то словам, предложениям найти нужный текст. И каталог зданий и возможно ответов на контрольные, лабораторные и тд
Можно брать всякое например:
t.me/crystschoolhelp
t.me/klass7_rb
t.me/gdz_by_7
t.me/klass6_rb
t.me/school_belarus
t.me/classrb10
t.me/nineclassrb
t.me/class8rb

**Comment by FaliedDedd** [comment]
Спасибо, приложения который ты скинул я декомпелирую. А по поводу тако я проверю что там

**Comment by AlexeiCrystal** [comment]
Photomath можно попробовать сделать оффлайн

**Comment by FaliedDedd** [comment]
Добавил ссылки на тгк, кнопки тоже пофиксил вроде все

**Comment by AlexeiCrystal** [comment]
У меня если что разрешение экрана: 2400x1080

**Comment by AlexeiCrystal** [comment]
Отступы в главном меню тоже не поменялись у меня. Как были не по центру, ближе к левому краю так и остались.
