### ISSUE TITLE
Отсупы и кнопки

### ISSUE THREAD

**Issue by AlexeiCrystal** [The-F-Project/EduCA#7]
1.25
В главном меню кнопки расположены ровно, но отступ от правого края больше чем от левого.
В учебника кнопки ещё больше перекосило, и там какое-то пустое место, будто бы там какой предмет убрали из списка, хз так это или нет.
![Screenshot_2024-12-28-13-06-38-767_org thefproject fedu](https://github.com/user-attachments/assets/8fd4fffb-d772-46cb-a5b1-73dc8ebf73d1)
![Screenshot_2024-12-28-13-06-24-910_org thefproject fedu](https://github.com/user-attachments/assets/bcb1b7d9-b628-4cdb-99bd-d1ee319fe97b)

Электронный дневник иногда приближается иногда нет.

**Comment by FaliedDedd** [comment]
![изображение](https://github.com/user-attachments/assets/94a7f648-f87a-4bac-b365-0780b70505bd)
макет должен быть такой. Отступы исправляю сейчас
