### ISSUE TITLE
Опять кнопки

### ISSUE THREAD

**Issue by AlexeiCrystal** [The-F-Project/EduCA#8]
Отступы в главном меню тоже не поменялись у меня. Как были не по центру, ближе к левому краю так и остались.
Не знаю что ты там пофиксил, но опять у меня кнопки по пизде пошли
![399085443-929f598f-9c09-492b-a632-0ebbe9b1ee75](https://github.com/user-attachments/assets/300016c3-254b-4276-95f8-1864682424ae)
Если это как-то поможет то моё разрешение экрана: 2400x1080

**Comment by FaliedDedd** [comment]
![photo_2024-12-28_17-32-39](https://github.com/user-attachments/assets/586a246c-0775-40c8-801a-d9db78548ffa)

У меня вот так, попробую что-то придумать с отступами
